name: Publish Go Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Publish to GitHub Packages
        run: |
          go mod tidy
          GATEWAY_PKG=github.com/AutoFTbot/OrderKuota-go
          GOOS=linux GOARCH=amd64 go build -o OrderKuota-go
          # example: mengemas sebagai artifact atau mengarsipkan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
