name: Manual Publish Go Module

on:
  workflow_dispatch:  # <-- ini memungkinkan manual trigger dari GitHub UI

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Build module (test)
      run: |
        go mod tidy
        go test ./...
        go build ./...

    - name: Publish (optional)
      run: |
        echo "Build selesai. Siap publish jika perlu."
